//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoDatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string County { get; set; }
        public int CustomerId { get; set; }
        public string StreetName { get; set; }
        public string StreetType { get; set; }
        public string Number { get; set; }
        public string Building { get; set; }
        public string Stairway { get; set; }
        public string Floor { get; set; }
        public string Door { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
