//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoDatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Address = new HashSet<Address>();
            this.Session = new HashSet<Session>();
        }
    
        public int Id { get; set; }
        public string Nev { get; set; }
        public string SharePointId { get; set; }
        public int ContactDetailId { get; set; }
        public string WLSzam { get; set; }
        public string Adoszam { get; set; }
        public string KSHSzam { get; set; }
        public string Cegjegyzekszam { get; set; }
        public Nullable<int> KonyvelesPenzneme { get; set; }
        public Nullable<int> BeszamoloPenzneme { get; set; }
        public string AdministratorName { get; set; }
        public string AdministratorPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        public virtual ContactDetail ContactDetail { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
    }
}
