//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoDatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldDescriptor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FieldDescriptor()
        {
            this.FieldValue = new HashSet<FieldValue>();
            this.PageDescriptor = new HashSet<PageDescriptor>();
        }
    
        public int Id { get; set; }
        public bool IsEditable { get; set; }
        public bool IsCalculated { get; set; }
        public bool IsMandatory { get; set; }
        public string AnykId { get; set; }
        public string Title { get; set; }
        public string Caption { get; set; }
        public string TypeName { get; set; }
        public string TypeOptions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldValue> FieldValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageDescriptor> PageDescriptor { get; set; }
    }
}
