//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoDatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageDescriptor
    {
        public int Id { get; set; }
        public int Order { get; set; }
        public string OrderCharacter { get; set; }
        public string Description { get; set; }
        public Nullable<int> ValueId { get; set; }
        public int PageId { get; set; }
        public Nullable<int> SectionGroup { get; set; }
        public Nullable<int> FieldId { get; set; }
    
        public virtual FieldDescriptor FieldDescriptor { get; set; }
        public virtual Page Page { get; set; }
    }
}
