//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoDatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.FieldValue = new HashSet<FieldValue>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime LastModifyDate { get; set; }
        public string Creator { get; set; }
        public string LastModifer { get; set; }
        public int CustomerId { get; set; }
        public int DocumentTypeId { get; set; }
        public int DocumentStateId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DocumentState DocumentState { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldValue> FieldValue { get; set; }
    }
}
