//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoDatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDescriptor
    {
        public int TableId { get; set; }
        public int FieldDescriptorId { get; set; }
        public string Caption { get; set; }
        public Nullable<int> ColumnOrder { get; set; }
        public int PageId { get; set; }
    
        public virtual FieldDescriptor FieldDescriptor { get; set; }
        public virtual Page Page { get; set; }
    }
}
