//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoDatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxesByCities
    {
        public int Id { get; set; }
        public string Megye { get; set; }
        public string City { get; set; }
        public decimal HelyiIparuzesiAdo { get; set; }
    }
}
